In [1]:
heights = [72,73,75,84,70,77]

In [2]:
heights * 2.54

TypeError: ignored

In [3]:
import numpy as np


In [5]:
np_heights = np.array(heights)

In [6]:
np_heights

array([72, 73, 75, 84, 70, 77])

In [7]:
type(np_heights)

numpy.ndarray

In [8]:
np_heights * 2.54

array([182.88, 185.42, 190.5 , 213.36, 177.8 , 195.58])

**Numpy comes with its own set of methods and operations**

In [12]:
list_1 = [1,2,3]
list_2 = [5,6,7]

list_1 + list_2

[1, 2, 3, 5, 6, 7]

In [13]:
np_list1 = np.array(list_1)
np_list2 = np.array(list_2)

np_list1 + np_list2

array([ 6,  8, 10])

In [14]:
type(np_list1)

numpy.ndarray