In [ ]:
import numpy as np

In [7]:
array_1= np.array([10,20,30,40,50])

array_2 = np.arange(5)

array_1 + array_2

array([10, 21, 32, 43, 54])

array([10, 21, 32, 43, 54])

In [10]:
array4 = np.array([1,2,3,4,5,6,4])

array_1 * array4

ValueError: ignored

In [12]:
array4   * 2

array([ 2,  4,  6,  8, 10, 12,  8])

In [14]:
array4**2

array([ 1,  4,  9, 16, 25, 36, 16])

In [17]:
array_5 = np.linspace(1,10, 5)

array_5

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [20]:
array1= np.array([10,20,30,40,50])
array2 = np.array([10,20,30,40,50])

np.hstack((array1, array2))

array([10, 20, 30, 40, 50, 10, 20, 30, 40, 50])

In [22]:
np.vstack((array1, array2))

array([[10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50]])

In [27]:
a = np.arange(12).reshape(3, 4)



In [31]:
print(8*12)

96


In [33]:
help(np.unravel_index)

Help on function unravel_index in module numpy:

unravel_index(...)
    unravel_index(indices, shape, order='C')
    
    Converts a flat index or array of flat indices into a tuple
    of coordinate arrays.
    
    Parameters
    ----------
    indices : array_like
        An integer array whose elements are indices into the flattened
        version of an array of dimensions ``shape``. Before version 1.6.0,
        this function accepted just one index value.
    shape : tuple of ints
        The shape of the array to use for unraveling ``indices``.
    
        .. versionchanged:: 1.16.0
            Renamed from ``dims`` to ``shape``.
    
    order : {'C', 'F'}, optional
        Determines whether the indices should be viewed as indexing in
        row-major (C-style) or column-major (Fortran-style) order.
    
        .. versionadded:: 1.6.0
    
    Returns
    -------
    unraveled_coords : tuple of ndarray
        Each array in the tuple has the same shape as the ``indices``
 

In [34]:
help(np.reshape)

Help on function reshape in module numpy:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
        c

In [43]:
arr_20 = np.arange(1, 21).reshape(4, 5)

arr_20 = arr_20[arr_20 %2 != 0].reshape(5, 2)
arr_20

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [3]:
import numpy as np
a = np.array([[1, 5],
 [3, 7],
 [4, 9]])

np.reshape(a, (1, -1))

array([[1, 5, 3, 7, 4, 9]])

In [5]:
math_array = np.linspace(0, np.pi, 5)
math_array

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

In [13]:
 np.sin(math_array)

array([0.00000000e+00, 7.07106781e-01, 1.00000000e+00, 7.07106781e-01,
       1.22464680e-16])

In [14]:
np.cos(math_array)

array([ 1.00000000e+00,  7.07106781e-01,  6.12323400e-17, -7.07106781e-01,
       -1.00000000e+00])

In [15]:
np.tan(math_array)

array([ 0.00000000e+00,  1.00000000e+00,  1.63312394e+16, -1.00000000e+00,
       -1.22464680e-16])

In [18]:
a = [1,2,3,4,5]
a= np.array(a)

np.power(a, 3)

array([  1,   8,  27,  64, 125])

In [20]:
np.exp(a)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [22]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [23]:
np.log2(a)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])

In [25]:
np.log2(a)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])

In [27]:
empty = np.empty(5)
empty

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])

In [30]:
empty = a * 5
empty

array([ 5, 10, 15, 20, 25])

In [32]:
np.multiply(empty, 12, out= empty)
empty

array([ 720, 1440, 2160, 2880, 3600])

In [38]:
long_array = np.zeros(10)
np.multiply(empty, 13, out= long_array[::2])

array([ 9360., 18720., 28080., 37440., 46800.])

In [40]:
long_array

array([ 9360.,     0., 18720.,     0., 28080.,     0., 37440.,     0.,
       46800.,     0.])

In [44]:
input_array = np.arange(5)
np.power(input_array, 2, out=empty)

array([ 0,  1,  4,  9, 16])

Aggregate operations

In [53]:
z = np.arange(1, 6)

np.add.reduce(z)

15

In [54]:
np.add.accumulate(z)

array([ 1,  3,  6, 10, 15])

In [55]:
np.multiply.reduce(z)

120

In [56]:
np.multiply.accumulate(z)

array([  1,   2,   6,  24, 120])

Rank of a matrix

In [59]:
a = np.array([[6,1,1],
              [4,-2,5],
              [2,8, 7]])
# number of independent row and columns

np.linalg.matrix_rank(a)

3

In [60]:
b = np.array([
    [1,2,3],
    [2,3,4],
    [3,5,7]
])
np.linalg.matrix_rank(b)

2

Trace of a matrix - sum of the diagonal

In [61]:
np.trace(a)

11

In [63]:
np.linalg.det(a)

-306.0

In [65]:
np.linalg.inv(a)

array([[ 0.17647059, -0.00326797, -0.02287582],
       [ 0.05882353, -0.13071895,  0.08496732],
       [-0.11764706,  0.1503268 ,  0.05228758]])

In [68]:
b = np.linalg.inv(a)
np.matmul(a, b)

array([[ 1.00000000e+00,  0.00000000e+00,  2.77555756e-17],
       [-1.38777878e-17,  1.00000000e+00,  1.38777878e-17],
       [-4.16333634e-17,  1.38777878e-16,  1.00000000e+00]])

In [70]:
a*b

array([[ 1.05882353, -0.00326797, -0.02287582],
       [ 0.23529412,  0.26143791,  0.4248366 ],
       [-0.23529412,  1.20261438,  0.36601307]])

In [72]:
np.linalg.matrix_power(a, 3)

array([[336, 162, 228],
       [406, 162, 469],
       [698, 702, 905]])