# Exercise Background

This small application based coding exercise is ment to expose you to the use of the numpy library as well as give you a taste of tasks that you might be needed to perform during machine learning. 

Usually, machine learning involves working on large data sets. This notebook will walk you through normalising the data and then dividing the data set into smaller subsets. It is recommended that while attempting each of the tasks visit the NumPy library to find the most appropriate function which can help you achieve the desired result. More often than not you will find the functions which you require prewritten in the library. The **numpy library** can be found [here.](https://numpy.org/doc/stable/) 

Without further ado, the first task is to mean normalise a data set. Mean normalising is a data transformation done to reduce the variations in the data set. For example, consider a data set which has integers between 0 and 10000. That is a lot of variation, and it becomes difficult to build ML algorithms on this data. So mean normalisation is done on such data, after the transformation, the mean of the data will be zero, and standard deviation will be 1.  Even though the actual values of data will change a lot, but the overall variation is still kept intact. If the concept of normalisation feels a bit unclear dont worry all of this will be covered in the future sections of this program. For now, let’s concentrate on the tasks at hand. 


# Task 1: Mean Normalisation: 

**Question 1.1** Create a 2D of random integers between 0 and 10,000 (including both 0 and 10,000) with 25000 rows and 15 columns. This will be the dataset you will use in the notebook. 

In [2]:
# import NumPy into Python
import numpy as np

# Create a 25000 x 15 ndarray with random integers in the interval [0, 10000].
X = np.random.randint(0,high = 10001, size = (25000,15))

# print the shape of X
X.shape

(25000, 15)

In [3]:
# print the first row of X
X[1]

array([9967, 2728,  200, 5170, 2370, 8255, 1341, 8350, 7475,  445, 5551,
       6351, 7124, 5684, 8752])

Now that you created the array we will mean normalize it. The equation for normalisaing the data is given below:

$\mbox{Norm_Col}_i = \frac{\mbox{Col}_i - \mu_i}{\sigma_i}$

where $\mbox{Col}_i$ is the $i$th column of $X$, $\mu_i$ is average of the values in the $i$th column of $X$, and $\sigma_i$ is the standard deviation of the values in the $i$th column of $X$. To put it simply, to find the new value of each element, you have to subtract the mean of respective column form that value and divide the result with the standard deviation of that columns. Now the question is, Why are these operations being done column-wise? That is because usually all the procedures in ML are done column-wise. So it will be beneficial for us to develop the habit of thinking about data column-wise.   

**Question 1.2** Find the mean and the standard deviation of each of the columns in the dataset. The result will be two 1D arrays with 15 elements each, representing the mean and standard deviation for each of the columns in the dataset.  

In [4]:
# Average of the values in each column of X
ave_cols = np.average(X, axis = 0)

# print ave_cols  
print ("ave_cols: \n", ave_cols,"\n")

# Standard Deviation of the values in each column of X
std_cols = np.std(X, axis = 0)

# print std_cols  
print ("std_cols: \n", std_cols,"\n")

ave_cols: 
 [4996.63828 5013.3106  4984.56124 4997.67812 4987.2784  5004.08892
 4999.14828 4987.4442  4998.67492 4978.88004 4970.86392 4977.5072
 5014.05708 4996.91752 4992.8592 ] 

std_cols: 
 [2880.08554483 2885.14635831 2886.6885787  2891.11321926 2890.45301431
 2897.40287892 2886.82851974 2888.65628668 2891.88247976 2894.55366653
 2879.94310167 2884.66260806 2889.27278609 2904.81740813 2868.86895796] 



**Question 1.3** Print the shape of each both the arrays, they should have 15 elements each.  

In [5]:
# Print the shape of ave_cols
print(ave_cols.shape)

# Print the shape of std_cols
print(std_cols.shape)

(15,)
(15,)


**Question 1.4** Now that you have mean and standard deviation calculated, it is time to apply the transformation to the dataset. 
 
**HINT** The broadcast property of NumPy can make this a lot easier. You can read about it [here](https://numpy.org/doc/stable/user/basics.broadcasting.html).
All you have to do is create one row of transformation values and repeat them through all the values.

In [6]:
# Mean normalize X
X_norm = (X - ave_cols)/std_cols

**Explanation of the solution:**
 
The shape X is (25000, 15), and the shape of  ave_cols is (15,). If their shapes are different, then how is it possible that the operation can be executed? It is because of the property of broadcasting. Broadcasting repeats the smaller arrays over and over until it becomes the same size as the larger array. In this case, it is straightforward to figure out how the repetition would have worked. The ave_cols will be repeated 25000 times, and the operation is executed. 
 
But be careful broadcasting also has some limitations, you can read about them in the link above. 

**Question 1.5** If the transformation has been performed correctly, the mean of elements in each column will be approximately 0. Also, the average of the **minimum** value in each column of X_norm and the average of the **maximum** value in each column of X_norm will have almost the same face value with opposite signs. Let’s confirm if the transformation has happened correctly. 

In [7]:
# Print the average of all the values of X_norm
print (np.average(X_norm))

# Print the average of the minimum value in each column of X_norm
print (np.average(X_norm.min(axis = 0)))

# Print the average of the maximum value in each column of X_norm
print (np.average(X_norm.max(axis = 0)))

8.981260180007666e-18
-1.7289181531823319
1.7336129803897007


Be mindful that the exact values might not match since the dataset was initialized using the random function. 

# Data Spliting 

After data processing, it is a regular practice in ML to split the dataset into three datasets. 

1. A Training Set
2. A Cross Validation Set
3. A Test Set

The ratios in which the data is split varies a bit from case to case. But the accepted standard 6:2:2 for train, test, and validation respectively. That is 60% for training data and so on. Again why is the data split or what is the signification of these smaller data sets? These questions are better left unanswered for now. 
The tanks assigned to you is to split the data in the given proportions randomly. 
For instance, if the data set had ten elements, this is how you would do it. 

In [8]:
# We create a random permutation of integers 0 to 9
np.random.permutation(10)

array([4, 0, 1, 8, 7, 6, 2, 3, 9, 5])

1. training set = 8,3,7,5,2,6
2. Cross Validation Set = 1,9
3. Test Set = 0,4

Notice, the propostion of the split has stayed the same, and the data points are randomply seleccted and data points do not repeat in different sets. 

**Question 2.1** Similarly, create a 1D array representing the indexes of the rows in the dataset X_norm. U can use the   `np.random.permutation()` function for randomising the indexes. 

In [9]:
# Create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`
row_indices = np.random.permutation(np.arange(0,25000))

In [10]:
# Print the shape of row_indices
row_indices.shape

(25000,)

**Question 2.2** Split the row indexes in the needed proportions. You can use the slicing methods you have learnt in this session to make the job easier.  

In [11]:
25000*0.6

15000.0

In [12]:
25000*0.2

5000.0

In [13]:
# Make any necessary calculations.
# You can save your calculations into variables to use later.
train = row_indices[:15000]
test = row_indices[15000:20000]
val  = row_indices[20000:]

**Question 2.4** Now make use of the indexes that you made to split the data also similarly once the data is split print the shape of each of the smaller data sets. `X_train` should have 15000 rows and 15 columns. `X_test` should have 5000 rows and 15 columns. `X_val` should have 5000 rows and 15 columns. 

In [14]:
# Create a Training Set
X_train = X_norm[train]

# Create a Cross Validation Set
X_Val = X_norm[test]

# Create a Test Set
X_test = X_norm[val]

In [15]:
# Print the shape of X_train
print(X_train.shape)

# Print the shape of X_crossVal
print(X_Val.shape)

# Print the shape of X_test
print(X_test.shape)

(15000, 15)
(5000, 15)
(5000, 15)


In [36]:
import numpy as np
first_array = np.array([[7, 13, 14],
[18, 10, 17],
[11, 12, 19]])

second_array = np.array([16, 6, 1]).reshape(1,-1)

third_array = np.array([[5, 8, 4, 3]])

final_array = np.append(first_array, second_array, axis= 0)

final_array = np.append(final_array, np.transpose(third_array), axis=1)

final_array

array([[ 7, 13, 14,  5],
       [18, 10, 17,  8],
       [11, 12, 19,  4],
       [16,  6,  1,  3]])